import { TeamInfo } from './teams-nba'

export const NHL_TEAMS: TeamInfo[] = [
  { id: 'ana', league: 'NHL', fullName: 'Anaheim Ducks', city: 'Anaheim', teamName: 'Ducks', abbreviation: 'ANA', venue: 'Honda Center', venueCity: 'Anaheim, CA', areaCodes: [714], conference: 'Western', division: 'Pacific', starPlayers: ['Trevor Zegras', 'Mason McTavish', 'Leo Carlsson'], coach: 'Greg Cronin' },
  { id: 'ari', league: 'NHL', fullName: 'Utah Hockey Club', city: 'Utah', teamName: 'Hockey Club', abbreviation: 'UTA', venue: 'Delta Center', venueCity: 'Salt Lake City, UT', areaCodes: [801], conference: 'Western', division: 'Central', alternateNames: ['Utah HC', 'Salt Lake City', 'Utah Mammoth'], starPlayers: ['Clayton Keller', 'Mikhail Sergachev', 'Lawson Crouse'], coach: 'Andre Tourigny' },
  { id: 'bos', league: 'NHL', fullName: 'Boston Bruins', city: 'Boston', teamName: 'Bruins', abbreviation: 'BOS', venue: 'TD Garden', venueCity: 'Boston, MA', areaCodes: [617, 857], conference: 'Eastern', division: 'Atlantic', starPlayers: ['David Pastrnak', 'Brad Marchand', 'Charlie McAvoy'], coach: 'Jim Montgomery' },
  { id: 'buf', league: 'NHL', fullName: 'Buffalo Sabres', city: 'Buffalo', teamName: 'Sabres', abbreviation: 'BUF', venue: 'KeyBank Center', venueCity: 'Buffalo, NY', areaCodes: [716], conference: 'Eastern', division: 'Atlantic', starPlayers: ['Tage Thompson', 'Dylan Cozens', 'JJ Peterka'], coach: 'Lindy Ruff' },
  { id: 'cgy', league: 'NHL', fullName: 'Calgary Flames', city: 'Calgary', teamName: 'Flames', abbreviation: 'CGY', venue: 'Scotiabank Saddledome', venueCity: 'Calgary, AB', areaCodes: [403], conference: 'Western', division: 'Pacific', starPlayers: ['Nazem Kadri', 'Jonathan Huberdeau', 'Rasmus Andersson'], coach: 'Ryan Huska' },
  { id: 'car', league: 'NHL', fullName: 'Carolina Hurricanes', city: 'Carolina', teamName: 'Hurricanes', abbreviation: 'CAR', venue: 'Lenovo Center', venueCity: 'Raleigh, NC', areaCodes: [919], conference: 'Eastern', division: 'Metropolitan', alternateNames: ['Raleigh'], starPlayers: ['Sebastian Aho', 'Andrei Svechnikov', 'Martin Necas'], coach: 'Rod Brind\'Amour' },
  { id: 'chi', league: 'NHL', fullName: 'Chicago Blackhawks', city: 'Chicago', teamName: 'Blackhawks', abbreviation: 'CHI', venue: 'United Center', venueCity: 'Chicago, IL', areaCodes: [312, 773], conference: 'Western', division: 'Central', starPlayers: ['Connor Bedard', 'Teuvo Teravainen', 'Seth Jones'], coach: 'Luke Richardson' },
  { id: 'col', league: 'NHL', fullName: 'Colorado Avalanche', city: 'Colorado', teamName: 'Avalanche', abbreviation: 'COL', venue: 'Ball Arena', venueCity: 'Denver, CO', areaCodes: [303, 720], conference: 'Western', division: 'Central', alternateNames: ['Denver'], starPlayers: ['Nathan MacKinnon', 'Cale Makar', 'Mikko Rantanen'], coach: 'Jared Bednar' },
  { id: 'cbj', league: 'NHL', fullName: 'Columbus Blue Jackets', city: 'Columbus', teamName: 'Blue Jackets', abbreviation: 'CBJ', venue: 'Nationwide Arena', venueCity: 'Columbus, OH', areaCodes: [614], conference: 'Eastern', division: 'Metropolitan', starPlayers: ['Kirill Marchenko', 'Zach Werenski', 'Cole Sillinger'], coach: 'Pascal Vincent' },
  { id: 'dal', league: 'NHL', fullName: 'Dallas Stars', city: 'Dallas', teamName: 'Stars', abbreviation: 'DAL', venue: 'American Airlines Center', venueCity: 'Dallas, TX', areaCodes: [214, 469, 972], conference: 'Western', division: 'Central', starPlayers: ['Jason Robertson', 'Roope Hintz', 'Miro Heiskanen'], coach: 'Peter DeBoer' },
  { id: 'det', league: 'NHL', fullName: 'Detroit Red Wings', city: 'Detroit', teamName: 'Red Wings', abbreviation: 'DET', venue: 'Little Caesars Arena', venueCity: 'Detroit, MI', areaCodes: [313], conference: 'Eastern', division: 'Atlantic', starPlayers: ['Dylan Larkin', 'Alex DeBrincat', 'Lucas Raymond'], coach: 'Derek Lalonde' },
  { id: 'edm', league: 'NHL', fullName: 'Edmonton Oilers', city: 'Edmonton', teamName: 'Oilers', abbreviation: 'EDM', venue: 'Rogers Place', venueCity: 'Edmonton, AB', areaCodes: [780], conference: 'Western', division: 'Pacific', starPlayers: ['Connor McDavid', 'Leon Draisaitl', 'Evan Bouchard'], coach: 'Kris Knoblauch' },
  { id: 'fla', league: 'NHL', fullName: 'Florida Panthers', city: 'Florida', teamName: 'Panthers', abbreviation: 'FLA', venue: 'Amerant Bank Arena', venueCity: 'Sunrise, FL', areaCodes: [954], conference: 'Eastern', division: 'Atlantic', alternateNames: ['Sunrise'], starPlayers: ['Matthew Tkachuk', 'Aleksander Barkov', 'Sam Reinhart'], coach: 'Paul Maurice' },
  { id: 'lak', league: 'NHL', fullName: 'Los Angeles Kings', city: 'Los Angeles', teamName: 'Kings', abbreviation: 'LAK', venue: 'Crypto.com Arena', venueCity: 'Los Angeles, CA', areaCodes: [213, 310, 323], conference: 'Western', division: 'Pacific', alternateNames: ['LA Kings', 'LA'], starPlayers: ['Anze Kopitar', 'Adrian Kempe', 'Kevin Fiala'], coach: 'Jim Hiller' },
  { id: 'min', league: 'NHL', fullName: 'Minnesota Wild', city: 'Minnesota', teamName: 'Wild', abbreviation: 'MIN', venue: 'Xcel Energy Center', venueCity: 'Saint Paul, MN', areaCodes: [651], conference: 'Western', division: 'Central', alternateNames: ['Saint Paul', 'St Paul'], starPlayers: ['Kirill Kaprizov', 'Brock Faber', 'Joel Eriksson Ek'], coach: 'John Hynes' },
  { id: 'mtl', league: 'NHL', fullName: 'Montreal Canadiens', city: 'Montreal', teamName: 'Canadiens', abbreviation: 'MTL', venue: 'Bell Centre', venueCity: 'Montreal, QC', areaCodes: [514], conference: 'Eastern', division: 'Atlantic', alternateNames: ['Habs'], starPlayers: ['Nick Suzuki', 'Cole Caufield', 'Juraj Slafkovsky'], coach: 'Martin St. Louis' },
  { id: 'nsh', league: 'NHL', fullName: 'Nashville Predators', city: 'Nashville', teamName: 'Predators', abbreviation: 'NSH', venue: 'Bridgestone Arena', venueCity: 'Nashville, TN', areaCodes: [615], conference: 'Western', division: 'Central', alternateNames: ['Preds'], starPlayers: ['Roman Josi', 'Filip Forsberg', 'Ryan O\'Reilly'], coach: 'Andrew Brunette' },
  { id: 'njd', league: 'NHL', fullName: 'New Jersey Devils', city: 'New Jersey', teamName: 'Devils', abbreviation: 'NJD', venue: 'Prudential Center', venueCity: 'Newark, NJ', areaCodes: [973, 201], conference: 'Eastern', division: 'Metropolitan', alternateNames: ['Newark'], starPlayers: ['Nico Hischier', 'Jack Hughes', 'Jesper Bratt'], coach: 'Sheldon Keefe' },
  { id: 'nyi', league: 'NHL', fullName: 'New York Islanders', city: 'New York', teamName: 'Islanders', abbreviation: 'NYI', venue: 'UBS Arena', venueCity: 'Belmont Park, NY', areaCodes: [516, 631], conference: 'Eastern', division: 'Metropolitan', alternateNames: ['NY Islanders', 'NY', 'Belmont Park'], starPlayers: ['Mathew Barzal', 'Bo Horvat', 'Noah Dobson'], coach: 'Patrick Roy' },
  { id: 'nyr', league: 'NHL', fullName: 'New York Rangers', city: 'New York', teamName: 'Rangers', abbreviation: 'NYR', venue: 'Madison Square Garden', venueCity: 'New York, NY', areaCodes: [212, 917], conference: 'Eastern', division: 'Metropolitan', alternateNames: ['NY Rangers', 'NY', 'MSG'], starPlayers: ['Artemi Panarin', 'Adam Fox', 'Chris Kreider'], coach: 'Peter Laviolette' },
  { id: 'ott', league: 'NHL', fullName: 'Ottawa Senators', city: 'Ottawa', teamName: 'Senators', abbreviation: 'OTT', venue: 'Canadian Tire Centre', venueCity: 'Ottawa, ON', areaCodes: [613], conference: 'Eastern', division: 'Atlantic', alternateNames: ['Sens'], starPlayers: ['Brady Tkachuk', 'Tim Stutzle', 'Drake Batherson'], coach: 'Travis Green' },
  { id: 'phi', league: 'NHL', fullName: 'Philadelphia Flyers', city: 'Philadelphia', teamName: 'Flyers', abbreviation: 'PHI', venue: 'Wells Fargo Center', venueCity: 'Philadelphia, PA', areaCodes: [215, 267], conference: 'Eastern', division: 'Metropolitan', alternateNames: ['Philly'], starPlayers: ['Sean Couturier', 'Travis Konecny', 'Cam York'], coach: 'John Tortorella' },
  { id: 'pit', league: 'NHL', fullName: 'Pittsburgh Penguins', city: 'Pittsburgh', teamName: 'Penguins', abbreviation: 'PIT', venue: 'PPG Paints Arena', venueCity: 'Pittsburgh, PA', areaCodes: [412], conference: 'Eastern', division: 'Metropolitan', alternateNames: ['Pens'], starPlayers: ['Sidney Crosby', 'Evgeni Malkin', 'Rickard Rakell'], coach: 'Mike Sullivan' },
  { id: 'sjs', league: 'NHL', fullName: 'San Jose Sharks', city: 'San Jose', teamName: 'Sharks', abbreviation: 'SJS', venue: 'SAP Center', venueCity: 'San Jose, CA', areaCodes: [408], conference: 'Western', division: 'Pacific', starPlayers: ['Macklin Celebrini', 'William Eklund', 'Fabian Zetterlund'], coach: 'Ryan Warsofsky' },
  { id: 'sea', league: 'NHL', fullName: 'Seattle Kraken', city: 'Seattle', teamName: 'Kraken', abbreviation: 'SEA', venue: 'Climate Pledge Arena', venueCity: 'Seattle, WA', areaCodes: [206], conference: 'Western', division: 'Pacific', starPlayers: ['Matty Beniers', 'Jared McCann', 'Vince Dunn'], coach: 'Dave Hakstol' },
  { id: 'stl', league: 'NHL', fullName: 'St. Louis Blues', city: 'St. Louis', teamName: 'Blues', abbreviation: 'STL', venue: 'Enterprise Center', venueCity: 'St. Louis, MO', areaCodes: [314], conference: 'Western', division: 'Central', alternateNames: ['Saint Louis'], starPlayers: ['Jordan Kyrou', 'Robert Thomas', 'Pavel Buchnevich'], coach: 'Drew Bannister' },
  { id: 'tbl', league: 'NHL', fullName: 'Tampa Bay Lightning', city: 'Tampa Bay', teamName: 'Lightning', abbreviation: 'TBL', venue: 'Amalie Arena', venueCity: 'Tampa, FL', areaCodes: [813], conference: 'Eastern', division: 'Atlantic', alternateNames: ['Tampa', 'Bolts'], starPlayers: ['Nikita Kucherov', 'Brayden Point', 'Victor Hedman'], coach: 'Jon Cooper' },
  { id: 'tor', league: 'NHL', fullName: 'Toronto Maple Leafs', city: 'Toronto', teamName: 'Maple Leafs', abbreviation: 'TOR', venue: 'Scotiabank Arena', venueCity: 'Toronto, ON', areaCodes: [416, 647], conference: 'Eastern', division: 'Atlantic', alternateNames: ['Leafs'], starPlayers: ['Auston Matthews', 'Mitch Marner', 'William Nylander'], coach: 'Craig Berube' },
  { id: 'van', league: 'NHL', fullName: 'Vancouver Canucks', city: 'Vancouver', teamName: 'Canucks', abbreviation: 'VAN', venue: 'Rogers Arena', venueCity: 'Vancouver, BC', areaCodes: [604, 778], conference: 'Western', division: 'Pacific', starPlayers: ['Elias Pettersson', 'Quinn Hughes', 'Brock Boeser'], coach: 'Rick Tocchet' },
  { id: 'vgk', league: 'NHL', fullName: 'Vegas Golden Knights', city: 'Vegas', teamName: 'Golden Knights', abbreviation: 'VGK', venue: 'T-Mobile Arena', venueCity: 'Las Vegas, NV', areaCodes: [702], conference: 'Western', division: 'Pacific', alternateNames: ['Las Vegas', 'Golden Knights', 'VGK'], starPlayers: ['Jack Eichel', 'Mark Stone', 'William Karlsson'], coach: 'Bruce Cassidy' },
  { id: 'wsh', league: 'NHL', fullName: 'Washington Capitals', city: 'Washington', teamName: 'Capitals', abbreviation: 'WSH', venue: 'Capital One Arena', venueCity: 'Washington, DC', areaCodes: [202], conference: 'Eastern', division: 'Metropolitan', alternateNames: ['DC', 'Caps'], starPlayers: ['Alex Ovechkin', 'Dylan Strome', 'Tom Wilson'], coach: 'Spencer Carbery' },
  { id: 'wpg', league: 'NHL', fullName: 'Winnipeg Jets', city: 'Winnipeg', teamName: 'Jets', abbreviation: 'WPG', venue: 'Canada Life Centre', venueCity: 'Winnipeg, MB', areaCodes: [204], conference: 'Western', division: 'Central', starPlayers: ['Kyle Connor', 'Mark Scheifele', 'Josh Morrissey'], coach: 'Scott Arniel' },
]

export function findNHLTeam(query: string): TeamInfo | undefined {
  const q = String(query ?? '').toLowerCase().trim()
  return NHL_TEAMS.find(t =>
    t.fullName.toLowerCase() === q ||
    t.city.toLowerCase() === q ||
    t.teamName.toLowerCase() === q ||
    t.abbreviation.toLowerCase() === q ||
    t.alternateNames?.some(n => String(n ?? '').toLowerCase() === q)
  )
}
